"""extraccion f2

Revisión: 0002
Anterior: '0001'
Fecha: 2026-10-06 18:52:20.929833
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extraccion_extracciones',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('proyecto_id', sa.Uuid(), nullable=False),
    sa.Column('articulo_id', sa.Uuid(), nullable=False),
    sa.Column('version_libro_id', sa.Uuid(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('estudios_reservados', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('salida', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('codificacion_ciega', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('anclas', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('hallazgos', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('acuerdo_campos_criticos', sa.Float(), nullable=True),
    sa.Column('iteraciones_validador', sa.Integer(), nullable=False),
    sa.Column('errores_validador', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('avisos_validador', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('uso_tokens', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('paso_fallido', sa.String(length=20), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('iniciada_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('terminada_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('extraccion_extracciones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_extraccion_extracciones_articulo_id'), ['articulo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_extraccion_extracciones_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_extraccion_extracciones_proyecto_id'), ['proyecto_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extraccion_extracciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_extraccion_extracciones_proyecto_id'))
        batch_op.drop_index(batch_op.f('ix_extraccion_extracciones_estado'))
        batch_op.drop_index(batch_op.f('ix_extraccion_extracciones_articulo_id'))

    op.drop_table('extraccion_extracciones')
    # ### end Alembic commands ###
