"""esquema inicial F1

Revisión: 0001
Anterior: ninguna
Fecha: 2026-10-06 07:27:05.050523
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proyectos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('correo', sa.String(length=200), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('rol', sa.String(length=30), nullable=False),
    sa.Column('hash_clave', sa.String(length=300), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo')
    )
    op.create_table('biblioteca_articulos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('proyecto_id', sa.Uuid(), nullable=False),
    sa.Column('nombre_archivo', sa.String(length=500), nullable=False),
    sa.Column('huella_sha256', sa.String(length=64), nullable=False),
    sa.Column('clave_almacen', sa.String(length=500), nullable=False),
    sa.Column('paginas', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('estado_anterior', sa.String(length=20), nullable=True),
    sa.Column('documento_estructurado_id', sa.Uuid(), nullable=True),
    sa.Column('error', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('excluido_motivo', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proyecto_id', 'huella_sha256', name='uq_articulo_huella')
    )
    with op.batch_alter_table('biblioteca_articulos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_biblioteca_articulos_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_biblioteca_articulos_proyecto_id'), ['proyecto_id'], unique=False)

    op.create_table('matriz_bases',
    sa.Column('proyecto_id', sa.Uuid(), nullable=False),
    sa.Column('clave_almacen', sa.String(length=500), nullable=False),
    sa.Column('nombre_archivo', sa.String(length=500), nullable=False),
    sa.Column('huella_sha256', sa.String(length=64), nullable=False),
    sa.Column('hoja', sa.String(length=200), nullable=False),
    sa.Column('importado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], ),
    sa.PrimaryKeyConstraint('proyecto_id')
    )
    op.create_table('matriz_filas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('proyecto_id', sa.Uuid(), nullable=False),
    sa.Column('estudio', sa.Integer(), nullable=False),
    sa.Column('documento', sa.Integer(), nullable=False),
    sa.Column('articulo_id', sa.Uuid(), nullable=True),
    sa.Column('origen', sa.String(length=10), nullable=False),
    sa.Column('version_libro_id', sa.Uuid(), nullable=True),
    sa.Column('version_desactualizada', sa.Boolean(), nullable=False),
    sa.Column('aprobada', sa.Boolean(), nullable=False),
    sa.Column('trazabilidad', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proyecto_id', 'estudio', name='uq_fila_estudio')
    )
    with op.batch_alter_table('matriz_filas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_matriz_filas_documento'), ['documento'], unique=False)
        batch_op.create_index(batch_op.f('ix_matriz_filas_proyecto_id'), ['proyecto_id'], unique=False)

    op.create_table('matriz_secuencias',
    sa.Column('proyecto_id', sa.Uuid(), nullable=False),
    sa.Column('siguiente_estudio', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], ),
    sa.PrimaryKeyConstraint('proyecto_id')
    )
    op.create_table('normas_versiones_libro',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('proyecto_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('contenido', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('publicada_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('normas_versiones_libro', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_normas_versiones_libro_proyecto_id'), ['proyecto_id'], unique=False)
        batch_op.create_index('uq_libro_activo', ['proyecto_id'], unique=True, postgresql_where=sa.text('activa'), sqlite_where=sa.text('activa'))

    op.create_table('outbox',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('proyecto_id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('datos', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('despachado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('intentos', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outbox', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outbox_despachado_en'), ['despachado_en'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbox_nombre'), ['nombre'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbox_proyecto_id'), ['proyecto_id'], unique=False)

    op.create_table('biblioteca_documentos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('proyecto_id', sa.Uuid(), nullable=False),
    sa.Column('articulo_id', sa.Uuid(), nullable=False),
    sa.Column('contenido', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('version_conversor', sa.String(length=100), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['articulo_id'], ['biblioteca_articulos.id'], ),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('biblioteca_documentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_biblioteca_documentos_articulo_id'), ['articulo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_biblioteca_documentos_proyecto_id'), ['proyecto_id'], unique=False)

    op.create_table('matriz_celdas',
    sa.Column('fila_id', sa.Uuid(), nullable=False),
    sa.Column('clave', sa.String(length=120), nullable=False),
    sa.Column('valor', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('estado_dato', sa.String(length=40), nullable=True),
    sa.Column('tipo_valor', sa.String(length=12), nullable=True),
    sa.Column('evidencias', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('inferencia', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('estado_revision', sa.String(length=20), nullable=False),
    sa.Column('historial', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['fila_id'], ['matriz_filas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('fila_id', 'clave')
    )
    with op.batch_alter_table('matriz_celdas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_matriz_celdas_estado_revision'), ['estado_revision'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matriz_celdas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matriz_celdas_estado_revision'))

    op.drop_table('matriz_celdas')
    with op.batch_alter_table('biblioteca_documentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_biblioteca_documentos_proyecto_id'))
        batch_op.drop_index(batch_op.f('ix_biblioteca_documentos_articulo_id'))

    op.drop_table('biblioteca_documentos')
    with op.batch_alter_table('outbox', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outbox_proyecto_id'))
        batch_op.drop_index(batch_op.f('ix_outbox_nombre'))
        batch_op.drop_index(batch_op.f('ix_outbox_despachado_en'))

    op.drop_table('outbox')
    with op.batch_alter_table('normas_versiones_libro', schema=None) as batch_op:
        batch_op.drop_index('uq_libro_activo', postgresql_where=sa.text('activa'), sqlite_where=sa.text('activa'))
        batch_op.drop_index(batch_op.f('ix_normas_versiones_libro_proyecto_id'))

    op.drop_table('normas_versiones_libro')
    op.drop_table('matriz_secuencias')
    with op.batch_alter_table('matriz_filas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matriz_filas_proyecto_id'))
        batch_op.drop_index(batch_op.f('ix_matriz_filas_documento'))

    op.drop_table('matriz_filas')
    op.drop_table('matriz_bases')
    with op.batch_alter_table('biblioteca_articulos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_biblioteca_articulos_proyecto_id'))
        batch_op.drop_index(batch_op.f('ix_biblioteca_articulos_estado'))

    op.drop_table('biblioteca_articulos')
    op.drop_table('usuarios')
    op.drop_table('proyectos')
    # ### end Alembic commands ###
